#pragma once


#define PREPROCESSOR_TO_STRING_INNER(X) #X
#define PREPROCESSOR_TO_STRING(X) PREPROCESSOR_TO_STRING_INNER(X)


#define PREPROCESSOR_JOIN_INNER(X, Y) X##Y
#define PREPROCESSOR_JOIN(X, Y) PREPROCESSOR_JOIN_INNER(X, Y)


#define INFINITY_PLATFORM_HEADER(Suffix) PREPROCESSOR_TO_STRING(PREPROCESSOR_JOIN(INFINITY_PLATFORM_HEADER_NAME, Suffix))