#pragma once


#if !defined(INFINITY_INCLUDE_PERMISSION_COMPILER_PLATFORM)
	#error "This file is not allowed to be included from any other file than CompilerPlatform.h."
#endif


#define DEBUG_BREAK() INFINITY_COMPILER_DEBUG_BREAK()
#define ASSUME(X) INFINITY_COMPILER_ASSUME(X)


#define DLL_EXPORT INFINITY_COMPILER_DLL_EXPORT
#define DLL_IMPORT INFINITY_COMPILER_DLL_EXPORT


#if defined(INFINITY_BUILD_ENABLE_FORCE_INLINE)
	#define INLINE INFINITY_COMPILER_INLINE
	#define FORCE_INLINE INFINITY_COMPILER_FORCE_INLINE

#elif defined(INFINITY_BUILD_ENABLE_INLINE)
	#define INLINE INFINITY_COMPILER_INLINE
	#define FORCE_INLINE INFINITY_COMPILER_INLINE
#else
	#define INLINE
	#define FORCE_INLINE
#endif


#define FORCE_NO_INLINE INFINITY_COMPILER_FORCE_NO_INLINE


