name: InfinityEngine

on: [push, pull_request]

jobs:

  windows:
    runs-on: windows-latest
    name: Windows
    
    steps:
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: latest
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup
        run: .\Setup.bat
      
      - name: Generate Project Files
        run: .\GenerateProjectFiles.bat
      
      - name: Debug Build
        run: msbuild InfinityEngine.sln -property:Configuration=Debug -property:Architecture=x64
      
      - name: Release Build
        run: msbuild InfinityEngine.sln -property:Configuration=Release -property:Architecture=x64
        
      - name: Production Build
        run: msbuild InfinityEngine.sln -property:Configuration=Production -property:Architecture=x64
      
      - name: Upload Artifacts (Production)
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: Windows Build 
          path: |
            Engine/Binaries/Production/*.exe
            Engine/Binaries/Production/*.dll
                  
  linux:
    runs-on: ubuntu-latest
    name: Linux
    
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup
        run: sh Setup.sh
      
      - name: Generate Project Files
        run: sh GenerateProjectFiles.sh
        
      - name: Debug Build
        run: make config=debug
      
      - name: Release Build
        run: make config=release
        
      - name: Production Build
        run: make config=production
      
      - name: Upload Artifacts (Production)
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: Linux Build
          path: |
            Engine/Binaries/Production/InfinityEngine-Sandbox
            Engine/Binaries/Production/*.so
      
  mac:
    runs-on: macOS-latest
    name: Mac

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup
        run: sh Setup.command
      
      - name: Generate Project Files
        run: sh GenerateProjectFiles.command
      
      - name: Debug Build
        run: xcodebuild build -workspace InfinityEngine.xcworkspace -scheme Sandbox -sdk macosx -configuration Debug
      
      - name: Release Build
        run: xcodebuild build -workspace InfinityEngine.xcworkspace -scheme Sandbox -sdk macosx -configuration Release
      
      - name: Production Build
        run: xcodebuild build -workspace InfinityEngine.xcworkspace -scheme Sandbox -sdk macosx -configuration Production

      - name: Upload Artifacts (Production)
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: Mac Build
          path: |
            Engine/Binaries/Production/InfinityEngine-Sandbox
            Engine/Binaries/Production/*.dylib